# Generated by Django 3.0.6 on 2020-06-16 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
